---
- name: LAB1 - Create VLAN Pool
  connection: local
  hosts: apic1

  vars:
    aci_conn: &aci_conn
      host: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: "{{ validate_certs }}"
      use_ssl: "{{ use_ssl }}"
 
    vlan_pools:
      - name: TEST-VLAN
        mode: static
        state: present
      - name: TEST2-VLAN
        mode: static
        state: present
      - name: TEST3-VLAN
        mode: dynamic
        state: present

    vlan_encap_blocks:
      - name: TEST
        from: 100
        to:   100
        pool: TEST-VLAN
        mode: static
        state: present
      - name: TEST
        from: 1000
        to:   1500
        pool: TEST2-VLAN
        mode: static
        state: present
      - name: TEST
        from: 2000
        to:   2500
        pool: TEST2-VLAN
        mode: static
        state: present

  tasks:
    - name: Create VLAN pools
      cisco.aci.aci_vlan_pool:
        <<: *aci_conn
        pool: "{{ item.name }}"
        pool_allocation_mode: "{{ item.mode }}"
        state: "{{ item.state }}"
      loop: "{{ vlan_pools }}" 

    - name: VLAN encap block
      cisco.aci.aci_vlan_pool_encap_block:
        <<: *aci_conn
        pool: "{{ item.pool }}"
        pool_allocation_mode: "{{ item.mode }}"
        block_name: "{{ item.name }}"
        block_start: "{{ item.from }}"
        block_end: "{{ item.to }}"
        state: "{{ item.state }}"
      loop: "{{ vlan_encap_blocks }}"