---
- name: LAB3
  connection: local
  hosts: apic1

  vars:
    aci_conn: &aci_login
      host: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: "{{ validate_certs }}"
      use_ssl: "{{ use_ssl }}"
      
  vars_files:
    - ../lab2/variables.yml
    - variables.yml

  tasks:
    - name: Leaf Access Port Policy Group
      cisco.aci.aci_interface_policy_leaf_policy_group:
        <<: *aci_login
        aep: "{{ item.aep }}"
        lag_type: "{{ item.lag_type }}"
        policy_group: "{{ item.interface_policy }}"
        cdp_policy: "{{ item.cdp_policy }}"
        lldp_policy: LLDP_DISABLE
        state: "{{ item.state }}"
      loop: "{{ interface_policy_groups }}"

    - name: Interface Leaf profile
      cisco.aci.aci_interface_policy_leaf_profile:
        <<: *aci_login
        interface_profile: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ interface_profiles }}"

    - name: Associate an Interface Access Port Selector to an Interface Policy Leaf Profile with a Policy Group
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        <<: *aci_login
        access_port_selector: "{{ item.name }}"
        interface_profile: "{{ item.profile_name }}"
        policy_group: "{{ item.interface_policy }}"
        port_blk: "{{ item.port_blk }}"
        from_port: "{{ item.fromPort }}"
        to_port: "{{ item.toPort }}"
        from_card: '1'
        to_card: '1'
        state: "{{ item.state }}"
      loop: "{{ interface_selectors }}"

    - name: Switch Leaf Profiles
      cisco.aci.aci_switch_policy_leaf_profile:
        <<: *aci_login
        leaf_profile: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ switch_profiles }}"

    - name: Adding a switch policy leaf profile selector associated Node Block range (w/ policy group)
      cisco.aci.aci_switch_leaf_selector:
        <<: *aci_login
        leaf_profile: "{{ item.profile_name }}"
        leaf: "{{ item.leaf_name }}"
        leaf_node_blk: node_block
        from: "{{ item.leaf_from }}"
        to: "{{ item.leaf_to }}"
        state: "{{ item.state }}"
      loop: "{{ switch_selectors }}"

    - name: Associating an interface selector profile to a switch policy leaf profile
      cisco.aci.aci_interface_selector_to_switch_policy_leaf_profile:
        <<: *aci_login
        leaf_profile: "{{ item.leaf_profile }}"
        interface_selector: "{{ item.interface_profile }}"
        state: "{{ item.state }}"
      loop: "{{ bind_interface_seletor_to_switch }}"
      