---
- name: LAB4
  connection: local
  hosts: apic1

  vars:
    aci_conn: &aci_login
      host: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: "{{ validate_certs }}"
      use_ssl: "{{ use_ssl }}"

  vars_files:
    - variables.yml

  tasks:
    - name: Check Tenant
      aci_tenant:
        <<: *aci_login
        tenant: "{{ tenant.name }}"
        state: query
      register: tenant_state

    - name: Application Profile
      aci_ap:
        <<: *aci_login
        tenant: "{{ item.tenant }}"
        ap: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ app_profiles }}"
      when: tenant_state.current

    - name: EPG
      aci_epg:
        <<: *aci_login
        tenant: "{{ item.tenant }}"
        bd: "{{ item.bd }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items: "{{ epgs }}"
      when: tenant_state.current

    - name: EPG to Domain
      aci_epg_to_domain:
        <<: *aci_login
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.name }}"
        domain: "{{ item.domain }}"
        domain_type: "{{ item.domain_type }}"
        state: "{{ item.state }}"
      with_items: "{{ epgs }}"
      when: tenant_state.current
