---
- name: LAB5-1
  connection: local
  hosts: apic1

  vars:
    aci_conn: &aci_login
      host: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: "{{ validate_certs }}"
      use_ssl: "{{ use_ssl }}"

  tasks:
    - name: API 호출 - 모든 인터페이스 상태 수집
      aci_rest:
        <<: *aci_login
        path: /api/class/ethpmPhysIf.json
        method: get
      register: ethpmPhysIf

    - name: 수집 결과를 파일로 저장 (Json포맷)
      copy:
        content: "{{ item.content | to_nice_json }}" 
        dest:    "{{ item.dest }}"
      loop:
        - content: "{{ ethpmPhysIf }}"
          dest: ethpmPhysIf.json
        - content: "{{ ethpmPhysIf | json_query('imdata[].ethpmPhysIf.attributes.{dn:dn, operSt:operSt, operMode:operMode, operSpeed:operSpeed}') }}"
          dest: ethpmPhysIf_mod.json