---
- name: LAB5-2
  connection: local
  hosts: apic1

  vars:
    aci_conn: &aci_login
      host: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: "{{ validate_certs }}"
      use_ssl: "{{ use_ssl }}"

  tasks:
    - name: l1PhysIf 수집
      aci_rest:
        <<: *aci_login
        path: /api/class/l1PhysIf.json
        method: get
      register: l1PhysIf

    - name: rmonDot3Stats 수집
      aci_rest:
        <<: *aci_login
        path: /api/class/l1PhysIf.json?query-target=children&target-subtree-class=rmonDot3Stats
        method: get
      register: rmonDot3Stats

    - name: rmonDot1d 수집
      aci_rest:
        <<: *aci_login
        path: /api/class/l1PhysIf.json?query-target=children&target-subtree-class=rmonDot1d
        method: get
      register: rmonDot1d

    - name: rmonEtherStats 수집
      aci_rest:
        <<: *aci_login
        path: /api/class/l1PhysIf.json?query-target=children&target-subtree-class=rmonEtherStats
        method: get
      register: rmonEtherStats

    - name: 수집 데이터를 파일로 저장
      copy:
        content: "{{ item.content | to_nice_json }}" 
        dest:    "{{ item.dest }}" 
      no_log: True
      loop:
        - content:  "{{ l1PhysIf | json_query('imdata[].l1PhysIf.attributes.dn')}}" 
          dest:     l1PhysIf.json   
        - content:  "{{ rmonDot3Stats | json_query('imdata[].rmonDot3Stats.attributes')}}" 
          dest:     rmonDot3Stats.json
        - content:  "{{ rmonDot1d | json_query('imdata[].rmonDot1d.attributes')}}" 
          dest:     rmonDot1d.json
        - content:  "{{ rmonEtherStats | json_query('imdata[].rmonEtherStats.attributes')}}" 
          dest:     rmonEtherStats.json

    - name: Json 파일을 엑셀 파일로 변환
      command: python3 files/json2xlsx_err.py

    # - name: 엑셀파일 이메일 전송 (엑셀파일 첨부)
    #   mail:
    #     host:     "{{ mail_host }}"
    #     port:     "{{ mail_port }}"
    #     username: "{{ mail_username }}"
    #     password: "{{ mail_password }}"
    #     from:     "{{ mail_sender }}"
    #     to :      "{{ mail_receiver }}"
    #     subject:  "[ACI Ansible HOL] 인터페이스 상태 알림 메일"
    #     subtype:  html
    #     body:     "<center><img width=1000 height=562 src=\"https://storage.googleapis.com/blogs-images/ciscoblogs/1/2020/05/Slide1-1.jpeg\"><h1>Cisco Customer Success는<br>고객 여러분의 성공을 도와드립니다.</h1></center>"
    #     secure:   starttls
    #     headers:  "Content-type=text/html"
    #     attach: 
    #       - "./인터페이스_에러.xlsx"